# Generated by Django 4.0.3 on 2022-03-05 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='name',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='institue',
            new_name='institute',
        ),
    ]
